apiVersion: v1
kind: Pod
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
spec:
  containers:
  - name: ${SERVICE_NAME}
    image: ${CONTAINER_IMAGE}
    ports:
    - containerPort: 3000
    volumeMounts:
      - name: workspace
        mountPath: /workspace
  volumes:
    - name: workspace
      hostPath:
        path: ${SERVICE_DIR}
        type: Directory